#####################################################################
## This file is part of the software CodeLab IDE and Simulators    ##
## For any question about CodeLab e-mail to codelab@univ-lemans.fr ##
#####################################################################

  >>> DO NOT DELETE ANY PROPERTY - THIS COULD AFFECT CODELAB
  >>> YOU MUST RESTART CODELAB TO TAKE INTO ACCOUNT ANY CHANGE
  >>> YOU CAN RESET THIS PROPERTY FILE VIA THE CODELAB MENU

#####################################################################
## Language of the application (en/fr/SYSTEM)
## Version check at CodeLab's opening (yes/no)
## Automatic reporting of Java exceptions (yes/no)
## Internal server port (any modification is risky)
## Internet connection waiting time in milliseconds

LANG=SYSTEM
CHECK_VERSION=yes
REPORT_EXCEPTIONS=no
COMPILE_TIMEOUT=5
PROGRAM_TIMEOUT=60
LOCAL_PORT=8500
TIME_OUT=5000

#####################################################################
## CodeLab file server host and port
## Proxy host and port (if you have one)
## Write PROXY_HOST=NO_PROXY if you don't have any proxy
## The MAX_FILE_SIZE threshold is defined in KBytes

CONNECTED_MODE=no

SERVER_HOST=
SERVER_PORT=

PROXY_HOST=NO_PROXY
PROXY_PORT=

MAX_FILE_SIZE=1024

#####################################################################
## Paths to interpreters and compilers
## You can also specify absolute paths
## Keep JAVA_HOME empty to use the CodeLab embedded JDK
## To find your JAVA_HOME on Linux: echo $JAVA_HOME or which java
## To find your Python interpreter on Linux: which python
## Specify DISABLED to ignore the language

GCC_CMD=gcc
GOLANG_CMD=go
HASKELL_CMD=ghc
PYTHON_CMD=python
JAVA_HOME=

#####################################################################
## Synthesizer oscillator (SINE/SQUARE/TRIANGLE/SAWTOOTH)

SYNTH_OSC=TRIANGLE

#####################################################################
## Configuration of the CodeLab's terminal
## BUFFER_SIZE: Buffer size (number of memorized lines)
## CONSOLE_SIZE: Height of the terminal (in pixels)
## CONSOLE_xxCOLOR: RGB values as 240:240:240 for example (optional)

BUFFER_SIZE=200
CONSOLE_SIZE=250

CONSOLE_PRINTCOLOR=
CONSOLE_INPUTCOLOR=
CONSOLE_ERRORCOLOR=
CONSOLE_FGCOLOR=
CONSOLE_BGCOLOR=

#####################################################################
## CodeLab code editor's properties

USER=John Doe
FONT_NAME=Cousine Regular
FONT_SIZE=14

#####################################################################
## Do not modify this section without knowing what it is about
## Inference engine after compilation and execution (yes/no)
## Display of the fact base in the log window (yes/no)

RETE_FLAG=no
PRINT_FACTS=no

#####################################################################
## Links to the language information and installation web pages
## You can replace them by the url of your choice

URL_C=https://www.learn-c.org/
URL_GO=https://go.dev/ref/spec
URL_JAVA=https://fr.wikibooks.org/wiki/Programmation_Java
URL_CLIPS=https://www.clipsrules.net/
URL_PYTHON=https://docs.python.org/fr/3/tutorial/index.html
URL_HASKELL=https://www.haskell.org/
URL_BLOCS=http://codelab.univ-lemans.fr/infoblocs/
URL_PROCESS=https://processing.org/reference

URL_INSTALL_C=https://codelab.univ-lemans.fr/infolang/install_c.html#linux
URL_INSTALL_GO=https://go.dev/dl/
URL_INSTALL_PYTHON=https://www.python.org/downloads/
URL_INSTALL_HASKELL=https://www.haskell.org/ghc/download.html
URL_INSTALL_NUMPY=https://numpy.org/install/
URL_INSTALL_MATPLOTLIB=https://matplotlib.org/stable/users/installing/
